### ISSUE TITLE
多虚拟桌面不显示

### ISSUE THREAD

**Issue by safeerHui** [SeptemberHX/dde-top-panel#11]
使用多虚拟桌面（工作空间）时候，只有第一个工作空间会显示top-bar，其他的虚拟桌面不显示

**Comment by SeptemberHX** [comment]
这个可以通过设置解决。
apt install systemsettings
然后打开 KDE 系统设置 -> 窗口管理 -> 窗口规则，新建规则，点击检测窗口属性后，选中顶栏，在大小和位置中勾选 桌面->强制全部桌面 即可。
