### ISSUE TITLE
[bug] Desktop icons go under the panel

### ISSUE THREAD

**Issue by SiamSami** [SeptemberHX/dde-top-panel#12]
The desktop icons go under the panel

![Screen Capture_select-area_20200628125446](https://user-images.githubusercontent.com/33563064/85940531-c2785b80-b93e-11ea-92c9-90666c6ea7cb.png)

**Comment by SeptemberHX** [comment]
Actually, the panel can "push" the icons away —— only when you start the top panel earlier than the dock. Sadly only one of the panel and the dock can "push" the icons away at the same time.
I think it is related to the dde-desktop.
