### ISSUE TITLE
[优化] 请求时间显示优化

### ISSUE THREAD

**Issue by cossonleo** [SeptemberHX/dde-top-panel#13]
首先 感谢大佬贡献出如此好用的应用
现在在时间显示很不清晰，可以优化一下吗
![截图录屏_选择区域_20200811054749](https://user-images.githubusercontent.com/20379044/89834987-6be57a80-db96-11ea-97de-5de4bee5e814.png)

**Comment by SeptemberHX** [comment]
这个问题是因为顶栏的高度太低，导致时间插件显示空间不足。然而这个时间插件是官方的，在 dde-dock 仓库里，所以我这边没办法。

可以使用论坛里 给出的附件：https://bbs.deepin.org/forum.php?mod=redirect&goto=findpost&ptid=198163&pid=747303&fromuid=229957
