### ISSUE TITLE
请求大大 能不能添加设置将关闭、最大化按钮放到最右边

### ISSUE THREAD

**Issue by cossonleo** [SeptemberHX/dde-top-panel#14]
因为个人习惯问题
请求大大 能不能添加设置将关闭、最大化按钮放到最右边

**Comment by SeptemberHX** [comment]
只要能接受每次操作按钮出现的时候所有的插件都会左移的话（我个人感觉很奇怪）
论坛上也有人提出类似的需求，所以准备开发。
现在操作按钮是和菜单、图标绑在一起的，拆开需要一些时间。

**Comment by cossonleo** [comment]
我用kde的时候，设置 按钮 一直显示，不论窗口是不是最大化或者有无窗口
大大可以参考一下

**Comment by SeptemberHX** [comment]
不最大化的时候显示按钮会显得很奇怪？毕竟窗口上有了按钮，显得很重复（还很占空间。。）

**Comment by cossonleo** [comment]
可能是我习惯了，我感觉一直显示也还好

**Comment by SeptemberHX** [comment]
0.5.5 已支持该功能。
