### ISSUE TITLE
dde-top-panel无法占位导致窗口最大化被dde-top-panel遮盖

### ISSUE THREAD

**Issue by eleveni386** [SeptemberHX/dde-top-panel#15]
"dde-top-panel" can not find qm files ("dde-top-panel_zh_CN.qm", "dde-top-panel_zh.qm")
===========> create top panel on "eDP1"
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Pass NET::WM2DesktopFileName to KWindowInfo
Pass NET::WM2WindowClass to KWindowInfo
Pass NET::WMVisibleIconName to KWindowInfo
Pass NET::WMVisibleName to KWindowInfo
Pass NET::WMIconName to KWindowInfo
Pass NET::WMVisibleName to KWindowInfo
"./dde-top-panel - 深度终端" "" "" "./dde-top-panel - 深度终端" "./dde-top-panel - 深度终端" "./dde-top-panel - 深度终端"
Not allowed to cQhange display mode
Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
strutArea is intersects with another screen.
1080 1920 0 QPoint(0,0) QSize(1920, 24)
QMetaObject::invokeMethod: No such method deepin_platform_plugin::DNoTitlebarWindowHelper::updateTranslucentBackgroundFromProperty()
Failed to update property: "updateTranslucentBackgroundFromProperty"
===========> create top panel on ":0.1"
Pass NET::WM2DesktopFileName to KWindowInfo
Pass NET::WM2WindowClass to KWindowInfo
Pass NET::WMVisibleIconName to KWindowInfo
Pass NET::WMVisibleName to KWindowInfo
Pass NET::WMIconName to KWindowInfo
Pass NET::WMVisibleName to KWindowInfo
"./dde-top-panel - 深度终端" "" "" "./dde-top-panel - 深度终端" "./dde-top-panel - 深度终端" "./dde-top-panel - 深度终端"
Not allowed to cQhange display mode
strutArea is intersects with another screen.
480 640 0 QPoint(0,0) QSize(640, 24)
QMetaObject::invokeMethod: No such method deepin_platform_plugin::DNoTitlebarWindowHelper::updateTranslucentBackgroundFromProperty()
Failed to update property: "updateTranslucentBackgroundFromProperty"
qt.qpa.xcb: QXcbConnection: XCB error: 148 (Unknown), sequence: 203, resource id: 0, major code: 140 (Unknown), minor code: 20
using dock local plugins dir: "/home/eleven/.local/lib/dde-top-panel/plugins/"
using dock plugins dir: "/usr/lib/dde-top-panel/plugins"
"DockPlugin" init plugin:  "datetime"
load plugins item:  "datetime" "datetime" DatetimeWidget(0x129e160)
"DockPlugin" init plugin finished:  "datetime"
"DockPlugin" init plugin:  "network"
onDevicesChanged:  ""
/usr/bin/proxychains4
load plugins item:  "network" "network-item-key" NetworkItem(0x12c4070)
"DockPlugin" init plugin finished:  "network"
"DockPlugin" init plugin:  "power"
"DockPlugin" init plugin finished:  "power"
"DockPlugin" init plugin:  "shutdown"
load plugins item:  "shutdown" "shutdown" ShutdownWidget(0x12df790)
"DockPlugin" init plugin finished:  "shutdown"
"DockPlugin" init plugin:  "sound"
load plugins item:  "sound" "sound-item-key" SoundItem(0x11af0e0)
"DockPlugin" init plugin finished:  "sound"
onDevicesChanged:  "{\"wireless\":[{\"Path\":\"/org/freedesktop/NetworkManager/Devices/2\",\"State\":100,\"Interface\":\"wlp2s0\",\"ClonedAddress\":\"60:F6:77:AD:0A:84\",\"HwAddress\":\"60:F6:77:AD:0A:84\",\"Driver\":\"iwlwifi\",\"Managed\":true,\"Vendor\":\"Intel Wireless 8265 / 8275\",\"UniqueUuid\":\"29590d32-3dc7-f4d5-a48c-350d7a8dc0e3\",\"UsbDevice\":false,\"ActiveAp\":\"/org/freedesktop/NetworkManager/AccessPoint/144\",\"SupportHotspot\":true,\"MobileNetworkType\":\"\",\"MobileSignalQuality\":0}]}"
"DockPlugin" init plugin:  "tray"
QLayout: Attempting to add QLayout "" to HoldContainer "", which already has a layout
QLayout: Attempting to add QLayout "" to HoldContainer "", which already has a layout
"DockPlugin" init plugin finished:  "tray"
Check connectivity using url: "https://www.baidu.com"
QNetworkReplyHttpImplPrivate::_q_startOperation was called more than once QUrl("https://www.baidu.com")
init Fashion mode tray plugin item
delay load 0 "keybord_layout" IndicatorTray(0xe88640)
using system tray plugins dir: "/usr/lib/dde-dock/plugins/system-trays"
QObject::connect: invalid null parameter
load plugins item:  "tray" "fashion-mode-item" FashionTrayItem(0x1323180)
===============init=============
QWidget::setMinimumSize: (/PluginsItem) Negative sizes (-1,24) are not possible
QWidget::setMinimumSize: (/PluginsItem) Negative sizes (-1,24) are not possible
"SystemTray" init plugin:  "disk-mount"
true

这是我启动时的提示, 主要是有两个问题. 一个是不知道为什么识别出来我有两个屏幕: "eDP1"和 ":0.1", 通过xrandr看的话. 我只有一个显示器处于激活状态.

二, 就是panel无法占位, 导致其他应用窗口最大化的时候, 被panel遮盖住.

**Comment by eleveni386** [comment]
Section "ServerLayout"
    Identifier "layout"
    Screen 0 "intel"
    #Screen 1 "nvidia"
EndSection

Section "Device"
    Identifier "intel"
    Driver "intel"
    BusID "0:2:0"
    Option "AccelMethod" "SNA"
EndSection

Section "Screen"
    Identifier "intel"
    Device "intel"
EndSection

Section "Device"
    Identifier "nvidia"
    Driver "nvidia"
    BusID "1:0:0"
    Option "ConstrainCursor" "off"
EndSection

Section "Screen"
    Identifier "nvidia"
    Device "nvidia"
    Option "AllowEmptyInitialConfiguration" "on"
    Option "IgnoreDisplayDevices" "CRT"
EndSection

我修改了一下我的xorg.conf配置, 将nvidia取消. 然后dde-top-panel 启动时 上面的两个问题都没有再发生了.  panel占位成功, 窗口最大化.不会被遮挡, create top panel 也不会创建两次了. 

, 不过我很好奇. 难道使用双显卡的 , 都会在一个屏幕内创建两次panel?

**Comment by SeptemberHX** [comment]
应该不是一定会发生吧，之前我台式机核显 + NVIDIA显卡，NVIDIA外接两个屏幕的时候是正常的。

屏幕识别我是直接用 Qt 的 QScreen 做的，所以应该是错误的配置导致了 Qt 识别到了多个显示器，然后出现了奇怪的问题，但是真正的原因不是很清楚，很大可能是深度的 Xorg 以及显卡驱动配置方面要背锅。
