### ISSUE TITLE
[bug] 顶栏在桌面上面，会覆盖其他图标

### ISSUE THREAD

**Issue by cossonleo** [SeptemberHX/dde-top-panel#16]
大佬， 可以修复吗， 这个还挺影响使用的

**Comment by SeptemberHX** [comment]
这个单靠 dde-top-panel 不行，图标防遮盖这个是 dde-desktop 配合 dde-dock 完成的，如果没有运行 dde-dock 的话，可以勾选 ignore dock 选项来解决，否则的话没有办法。
