### ISSUE TITLE
dde-top-panel "kidnap" to dde-dock

### ISSUE THREAD

**Issue by peteromio** [SeptemberHX/dde-top-panel#17]
for some reason when I run dde-top-panel my dock appears on top next to it, and it is in "keed shown" mode, if I try to put the dock at the bottom it immediately goes back up

I am using deepin v20 (1001) and dde-top-panel 0.5.5

**Comment by SeptemberHX** [comment]
Please uncheck the "Ignore Dock" option in settings.

Seems I set it to enable on default by mistake. It will be fixed soon.

**Comment by peteromio** [comment]
it worked, thanks
