### ISSUE TITLE
三大按钮Bug

### ISSUE THREAD

**Issue by Bluequarks** [SeptemberHX/dde-top-panel#18]
自定义按钮图标后每次自启动不会加载自定义的，去设置里点一点按钮相关的设置就好了

**Comment by SeptemberHX** [comment]
版本是多少？我这边没有复现。修改完配置后，`cat ~/.config/dde-top-panel/top-panel.conf` 看一下 closeIcon, minIcon, unmaxIcon 那几项有没有变成你设置的图标。

**Comment by Bluequarks** [comment]
版本0.5.5，top-panel.conf里确实是我自定义的，但是刚启动时不会加载，改动一下设置就好了（随便改一下就行，不是按钮的选项都行）

**Comment by Bluequarks** [comment]
https://gitee.com/bluequantum/temp/blob/master/Screen%20Capture_select-area_20200831082227.gif
录屏复现

**Comment by SeptemberHX** [comment]
[dde-top-panel.zip](https://github.com/SeptemberHX/dde-top-panel/files/5148072/dde-top-panel.zip)

已定位并尝试修复，试试看

**Comment by Bluequarks** [comment]
目前可以了
火速修复，赞！
