### ISSUE TITLE
on deepin 20 latest update main bar forced to top

### ISSUE THREAD

**Issue by bitgandtter** [SeptemberHX/dde-top-panel#19]
Wen top panel starts move the main bar to the top an there is no way to move it back to bottom

**Comment by SeptemberHX** [comment]
Please uncheck the "Ignore Dock" option in settings.

Seems I set it to enable on default by mistake. It will be fixed in next release.

**Comment by bitgandtter** [comment]
Excellent it works. As a recommendation including nicer icons for close minimize will be great and also try to build .deb for easy of install. That said this its excellent work

**Comment by SeptemberHX** [comment]
> Excellent it works. As a recommendation including nicer icons for close minimize will be great and also try to build .deb for easy of install. That said this its excellent work

Thanks for your suggestions. I will try to build a deb package for it.
