### ISSUE TITLE
Deepin dock position changed to top

### ISSUE THREAD

**Issue by laradvance** [SeptemberHX/dde-top-panel#20]
When launch this top bar, dock position move to the top and cannot change

Deepin 20.1002

**Comment by SeptemberHX** [comment]
Please uncheck the "Ignore Dock" option in settings.

Seems I set it to enable on default by mistake. It will be fixed in next release.

**Comment by probonopd** [comment]
I am having the same issue. Deepin Dock is moved to the top, and no global menubar (AppMenu) is shown.

**Comment by SeptemberHX** [comment]
> Thanks @SeptemberHX for this very useful software. It is the main thing that is missing in Deepin 20 in my opinion.
> 
> I am having the same issue. Deepin Dock is moved to the top, and no global menubar (AppMenu) is shown.
> 
> > Please uncheck the "Ignore Dock" option in settings.
> 
> Where can this setting be found?

Right click any empty area of the panel, and a menu widget should appear.
