### ISSUE TITLE
Does not show menu for dde applications

### ISSUE THREAD

**Issue by probonopd** [SeptemberHX/dde-top-panel#22]
Does not show menu in the dde-top-panel for dde applications:

![Screen Capture_20201002204101](https://user-images.githubusercontent.com/2480569/94999824-63208c00-05bc-11eb-97a2-864adb7e1f18.png)

It works for Chromium, which is not a dde application.

**Comment by SeptemberHX** [comment]
I'm afraid nothing I can do with it. 
DDE applications are based on DTK, which is developed by deepin based on Qt. They implemented their own menu classes, and the new classes don't support global menu. So it is impossible for dde-top-panel to show global menu for them.
The only solution is that deepin makes their applications support global menu officially.

**Comment by probonopd** [comment]
Thanks @SeptemberHX. I will open a feature request for Deepin.
