### ISSUE TITLE
run instruction

### ISSUE THREAD

**Issue by aykutkaraca** [SeptemberHX/dde-top-panel#27]
I am newbie, run instructions arent clear. Could you please real commands to be copied and pasted. cp *.xml doesnt work. and xml files are all in different folders...thanks for developing this though I hope I can use it.

**Comment by SeptemberHX** [comment]
If you are using Deepin V20, than:
```shell
wget https://github.com/SeptemberHX/dde-top-panel/releases/download/0.5.5/dde-top-panel-0-5-5.zip
unzip dde-top-panel-0-5-5.zip
cd dde-top-panel-0-5-5
sudo cp *.xml /usr/share/glib-2.0/schemas
sudo glib-compile-schemas /usr/share/glib-2.0/schemas

# run
./dde-top-panel
```

For other distributions, I am not sure package names of the dependencies as detailed in readme, and I cannot help about it.
After building from source with commands below:
```shell
git clone https://github.com/SeptemberHX/dde-top-panel.git
cd dde-top-panel
mkdir build
cd build
cmake ..
make
```

run
```shell
sudo cp ../xml/com.deepin.dde.toppanel.gschema.xml /usr/share/glib-2.0/schemas
sudo glib-compile-schemas /usr/share/glib-2.0/schemas
```

and
```shell
./frame/dde-top-panel
```

**Comment by aykutkaraca** [comment]
Hi there,

I think it must be :
`sudo cp ./xml/com.deepin.dde.toppanel.gschema.xml /usr/share/glib-2.0/schemas`
if you are in the folder you extracted.

and even doing correctly and doing the glib thing, there is no file ./frame/dde-top-panel

Do we have to compile it?

**Comment by SeptemberHX** [comment]
> Hi there,
> 
> I think it must be :
> `sudo cp ./xml/com.deepin.dde.toppanel.gschema.xml /usr/share/glib-2.0/schemas`
> if you are in the folder you extracted.
> 
> and even doing correctly and doing the glib thing, there is no file ./frame/dde-top-panel
> 
> Do we have to compile it?
> 
> edit also cd dde-top-panel-0-5-5 must be
> `cd 0.5.5`
> 
> Additional problems: It cant disable the dde-dock. It keeps re-appearing on top. And dde-top-panel doesnt load automatically each login. How can we establish that?

Thanks for pointing out the mistakes.
`./frame/dde-top-panel` is only shown when you compile it from source.
If you download the zip file in the release page, then you can unzip it, cd into it, and run `dde-top-panel` file.
If you are using Deepin V20, I recommend to download the pre-build version in the release page.

For the autostart, currently it is not supported yet. You need to create a desktop file for it and put the desktop file to ~/.config/autostart as detailed in [Ask Ubuntu](https://askubuntu.com/questions/963675/how-to-start-application-when-system-boots-using-a-desktop-file).
And you cannot disable dde-dock by dde-top-panel. Renaming /bin/dde-dock to /bin/dde-dock.bak is a good choice I think.

**Comment by aykutkaraca** [comment]
Yes I was finally able to load it automatically and disable dde-dock but it is not showing the open applications. The plugins are too small as you cant change the height of the panel. And some apps still show the title bar...I stopped using it because it didn't solve my problem related to dstetime plugin. But nice work . Please keep it up!!!
