### ISSUE TITLE
wine 软件图标在 dde-top-panel 的 tray 托盘中无法操作

### ISSUE THREAD

**Issue by traversalnat** [SeptemberHX/dde-top-panel#31]
qq 微信等wine软件图标在 dock 的托盘中可以正常操作,但是无法在 top-panel 中操作, 但是网易云之类的原生应用可以操作.

**Comment by SeptemberHX** [comment]
这个是deepin在实现libtray的方式导致的，wine程序的托盘图和系统原生的是不一样的，会给每个托盘图标新建一个窗口然后通过窗口ID来控制，但是这样做会导致同时只能有一个托盘能够拿到正确的图标窗口ID。

除非改托盘插件，否则没办法解决。所以这个问题和顶栏无关。现在我暂时也没有精力开坑libtray了，不过还有个折中方案：想办法去掉系统dock上的libtray，但是不能直接删掉插件文件，只能试试论坛里其他人魔改后的类macos的dock

**Comment by SeptemberHX** [comment]
这个是deepin在实现libtray的方式导致的，wine程序的托盘图和系统原生的是不一样的，会给每个托盘图标新建一个窗口然后通过窗口ID来控制，但是这样做会导致同时只能有一个托盘能够拿到正确的图标窗口ID。

除非改托盘插件，否则没办法解决。所以这个问题和顶栏无关。现在我暂时也没有精力开坑libtray了，不过还有个折中方案：想办法去掉系统dock上的libtray，但是不能直接删掉插件文件，只能试试论坛里其他人魔改后的类macos的dock
