### ISSUE TITLE
停用时原最大最小化按钮消失

### ISSUE THREAD

**Issue by ayuayue** [SeptemberHX/dde-top-panel#33]
有时候全局菜单会失效，但是停用dde-top-panel后原来的三大金刚键没了，比如goland phpstorm。gt2.0,3.0的配置都更改为初始值也没有办法显示。

**Comment by ayuayue** [comment]
![image](https://user-images.githubusercontent.com/44837611/109760791-456a5800-7c2a-11eb-8a52-17b7062bc6f5.png)

**Comment by ayuayue** [comment]
更改kwin.conf后还原了

**Comment by ayuayue** [comment]
kwinrc

**Comment by ayuayue** [comment]
> 更改kwin.conf后还原了
~/.config/kwinrc
[Windows]
BorderlessMaximizedWindows=false

**Comment by SeptemberHX** [comment]
是一些特定软件失效还是全部都不行？失效的时候，globalmenu 进程还正常么？有没有什么异常输出？

**Comment by ayuayue** [comment]
> 是一些特定软件失效还是全部都不行？失效的时候，globalmenu 进程还正常么？有没有什么异常输出？

部分软件，系统软件是正常的。应该是kwin配置了全屏关闭标题栏导致的，有些软件在deepin上是有一个大的标题栏的，最上方很突兀，比如默认的Google浏览器或没有设置过的vscode
