### ISSUE TITLE
按照论坛的方式配置完成之后，无法正常使用

### ISSUE THREAD

**Issue by JasonYan025** [SeptemberHX/dde-top-panel#34]
启动dde-top-panel之后，自带的dock会强制移动到顶部，无法修改位置，也无法设置隐藏。不知道算不算是bug

**Comment by SeptemberHX** [comment]
右键设置里，取消勾选 Ignore Dock 即可。
默认设置错误，已经更新了

**Comment by JasonYan025** [comment]
好吧，搞这个。把我系统搞挂了。我还是缺少折腾精神。。。。。。。。。。。。。。

**Comment by JasonYan025** [comment]
我也不知道为啥，deeppin的整个桌面直接全挂了。进去就是黑屏。啥也看不到了。我装了英伟达的闭源显卡驱动。现在还是老老实实的用win吧 。。。。。。
