### ISSUE TITLE
get error like this when make from the latest source. 

### ISSUE THREAD

**Issue by ancion** [SeptemberHX/dde-top-panel#35]
![20210512124946](https://user-images.githubusercontent.com/49437191/117920403-62ee2900-b321-11eb-902a-687c055620bd.png)

**Comment by SeptemberHX** [comment]
系统版本是？

**Comment by ancion** [comment]
20.2



---Original---
From: ***@***.***&gt;
Date: Wed, May 12, 2021 12:58 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [SeptemberHX/dde-top-panel] get error like this when make from the latest source.  (#35)




 
系统版本是？

**Comment by SeptemberHX** [comment]
我这边复现不了，Deepin v20.2。看着可能是 dtk 相关的包的版本装错了，看一下装的 dev 开发包版本是多少

**Comment by ancion** [comment]
![截图_选择区域_20210512193726](https://user-images.githubusercontent.com/49437191/117969157-a49ac600-b359-11eb-8f48-e84cc3810150.png)
主要是这些版本的包

**Comment by SeptemberHX** [comment]
![image](https://user-images.githubusercontent.com/18042424/117973491-0b6eae00-b35f-11eb-98f3-9b167d24cfb5.png)

应该是 core  和 widget 两个包版本不对
