### ISSUE TITLE
微信托盘消失

### ISSUE THREAD

**Issue by eleveni386** [SeptemberHX/dde-top-panel#36]
启动微信之后, 顶栏上还有托盘. 但是过了不久, 微信的托盘图标就消失了. 消失前, dde-top-panel会闪一下.

**Comment by SeptemberHX** [comment]
应该与顶栏无关，托盘是独立插件，建议检查托盘插件是否和系统版本一致

**Comment by eleveni386** [comment]
> 应该与顶栏无关，托盘是独立插件，建议检查托盘插件是否和系统版本一致

用自带的dde-dock, 微信的托盘没消失, 而且我的libtray.so 也是从dde-dock的插件目录里面copy出来的.

**Comment by eleveni386** [comment]
> 应该与顶栏无关，托盘是独立插件，建议检查托盘插件是否和系统版本一致

而且, 我重新启动一下dde-top-panel, 微信的托盘又重新出现了.

**Comment by SeptemberHX** [comment]
其它wine程序的托盘有没有类似问题？

**Comment by eleveni386** [comment]
> 其它wine程序的托盘有没有类似问题？

也有, 而且, 还有发现一个问题. 我从dde-dock里面copy了一个蓝牙的插件过来, 当我正在微信中聊天正欢的时候. 突然dde-top-panel一阵抽搐, 然后微信托盘, 蓝牙图标. 都消失了. 
我莫名其妙, 不知道怎么dde-top-panel突然高潮了.

**Comment by SeptemberHX** [comment]
看起来像是 dde-dock 插件的显示、刷新等机制调整过，后面我和 dde-dock 对比一下看看改了些啥

**Comment by SeptemberHX** [comment]
重复 #37

**Comment by SeptemberHX** [comment]
啊，反了

**Comment by SeptemberHX** [comment]
试试看这个版本，从 dde-dock 那边合并了中间时间的所有提交。用 QQ 试了一下，暂时没有出现你说的问题。

如果用了 dde-istate-menus 插件，需要先删掉他，不然会崩。
[dde-top-panel.zip](https://github.com/SeptemberHX/dde-top-panel/files/6642048/dde-top-panel.zip)

**Comment by eleveni386** [comment]
> 试试看这个版本，从 dde-dock 那边合并了中间时间的所有提交。用 QQ 试了一下，暂时没有出现你说的问题。
> 
> 如果用了 dde-istate-menus 插件，需要先删掉他，不然会崩。
> 
> [dde-top-panel.zip](https://github.com/SeptemberHX/dde-top-panel/files/6642048/dde-top-panel.zip)

用了这个版本, 也存在, 我是这样触发的, 启动微信之后, 右键点击sogou的托盘图标. 就会触发panel的闪烁. 这个时候微信托盘和蓝牙托盘就消失了. 但是我其他的托盘图标没问题, 比如我的qv2ray, 坚果网盘

**Comment by SeptemberHX** [comment]
![2021-06-13 16 47 37](https://user-images.githubusercontent.com/18042424/121800950-436f5680-cc67-11eb-859b-dc7683287aad.gif)

这边还是无法复现。微信我这边装上后不知道为什么闪退，用QQ代替测试了一下，没有出现你说的情况。

可能和显卡驱动有关？你的是 N 卡么？

**Comment by eleveni386** [comment]
> ![2021-06-13 16 47 37](https://user-images.githubusercontent.com/18042424/121800950-436f5680-cc67-11eb-859b-dc7683287aad.gif)
> 
> 这边还是无法复现。微信我这边装上后不知道为什么闪退，用QQ代替测试了一下，没有出现你说的情况。
> 
> 可能和显卡驱动有关？你的是 N 卡么？

是N卡. 你能不能给一个开启了debug的程序给我. 我把日志提交给你分析一下?

**Comment by eleveni386** [comment]
> ![2021-06-13 16 47 37](https://user-images.githubusercontent.com/18042424/121800950-436f5680-cc67-11eb-859b-dc7683287aad.gif)
> 
> 这边还是无法复现。微信我这边装上后不知道为什么闪退，用QQ代替测试了一下，没有出现你说的情况。
> 
> 可能和显卡驱动有关？你的是 N 卡么？

你试试鼠标中键, 点击sogou输入法. 能不能触发.

**Comment by SeptemberHX** [comment]
我怀疑是N卡驱动问题，我的电脑只有核显。你可以试着先切换到核显看看还有没有这个问题。

这边也没有日志，插件加载部分都是官方代码，我也没额外加日志，我暂时也没头绪问题是在哪里。

**Comment by eleveni386** [comment]
> 我怀疑是N卡驱动问题，我的电脑只有核显。你可以试着先切换到核显看看还有没有这个问题。
> 
> 这边也没有日志，插件加载部分都是官方代码，我也没额外加日志，我暂时也没头绪问题是在哪里。

经过这两天的尝试. dde-top-panel 好像没有自动高潮了.  我自检发现, 好像全局菜单的应用程序我没启用. 但是我又以为我启用了全局菜单. 所有配置文件也是按照你全局菜单的要求配置的. 我将全局菜单的程序启用之后. dde-top-panel就没自动高潮过了.

**Comment by SeptemberHX** [comment]
dde-globalmenu-service 关掉后，我这边还是没有复现，包括鼠标的各个按键 + 微信，都没有出现类似情况。

虽然最后貌似你那边又好了，但是依然不知道为什么，全局菜单按理说和托盘毫无关联才对。先这样吧，后面再出问题的时候再看看。。
