### ISSUE TITLE
deepin-mail的托盘图标无法双击

### ISSUE THREAD

**Issue by eleveni386** [SeptemberHX/dde-top-panel#37]
这个不确定是不是顶栏的问题, deepin-mail 最小化托盘后, 在顶栏上无法通过双击重新打开主窗口. 而右键只有一个退出功能

**Comment by SeptemberHX** [comment]
应该与顶栏无关，托盘是独立插件，建议检查托盘插件是否和系统版本一致，以及 dde-dock 上是否也有该问题

**Comment by SeptemberHX** [comment]
duplicate with #36
