### ISSUE TITLE
与网易云音乐存在冲突

### ISSUE THREAD

**Issue by chenxiex** [SeptemberHX/dde-top-panel#38]
网易云音乐更改下载目录后需要自动重启，此时如果开着dde-top-panel（有libtray.so插件加载）就会dde-top-panel卡死，网易云音乐无法重启；关闭dde-top-panel后，重新启动网易云音乐进行相同操作，则可以自动重启。

**Comment by SeptemberHX** [comment]
这边无法复现问题：

[Imgur](https://i.imgur.com/9cnWXcU.gifv)

测试系统版本：20.2.2
dde-top-panel版本：0.5.7

**Comment by chenxiex** [comment]
> 这边无法复现问题：
> 
> [Imgur](https://i.imgur.com/9cnWXcU.gifv)
> 
> 测试系统版本：20.2.2
> dde-top-panel版本：0.5.7
> 
> gif 文件较大（33MB），可能需要加载好一会
> 
> 你的系统版本和 panel 版本是？

系统是deepin20.2.2，panel版本0.5.7。
我试了下，转移到cloudmusic目录没有问题，转移到音乐目录会出问题。
[http://alspace.glitch.me/%E5%9B%BE%E5%BA%8A/c8202b8d05d0f90ae1f33ce04840e9d8.gif
](url)

**Comment by SeptemberHX** [comment]
依旧无法复现。。。无论是转移到 cloudmusic 还是 music 还是任意路径、中文路径都没有复现。

你的网易云音乐哪里来的？我无论是商店安装的还是官网下载的Ubuntu版本，选择迁移目录都不是深度的文件管理器。

**Comment by chenxiex** [comment]
> 依旧无法复现。。。无论是转移到 cloudmusic 还是 music 还是任意路径、中文路径都没有复现。
> 
> 你的网易云音乐哪里来的？我无论是商店安装的还是官网下载的Ubuntu版本，选择迁移目录都不是深度的文件管理器。是做了什么修改么？
> 
> 还有 libtray.so 是最新版本还是旧的版本？

网易云音乐是从星火商店下载的版本。
libtray.so从deepin20.2.1升级上来之后的确没有重新覆盖……这个每次系统升级都要重新覆盖一遍吗？

**Comment by SeptemberHX** [comment]
是的，最好每次升级后都重新覆盖，不然会错过一些 bug 修复

**Comment by chenxiex** [comment]
> 是的，最好每次升级后都重新覆盖，不然会错过一些 bug 修复

大佬能分享一个吗？我以为用不到了结果删掉了……

**Comment by SeptemberHX** [comment]
`apt reinstall dde-dock` 即可重新安装 dock，插件也包含在内。

**Comment by chenxiex** [comment]
> `apt reinstall dde-dock` 即可重新安装 dock，插件也包含在内。

我这里的网易云音乐也神奇的变成了gtk的文件选框，而且根本切换不了目录了。既然无法复现了，现close了吧。
