### ISSUE TITLE
class QTextBrowser’ has no member named ‘setMarkdown’

### ISSUE THREAD

**Issue by ipyffor** [SeptemberHX/dde-top-panel#40]
dde-top-panel/build/frame/dde-top-panel_autogen/include/ui_mainsettingwidget.h:1055:22: error: ‘class QTextBrowser’ has no member named ‘setMarkdown’; did you mean ‘setMask’?

**Comment by SeptemberHX** [comment]
代码里没有显示调用过 setMarkdown，而是 mainsettingwidget.ui 里有个 markdown 属性，然后自动从 ui 文件生成的。5.14 版本后引入。

![image](https://user-images.githubusercontent.com/18042424/130357135-cc1102f6-b997-4dd0-a034-3bbb344b914f.png)

![image](https://user-images.githubusercontent.com/18042424/130357222-6fc8bf9e-ff09-4720-97f2-8f97664c987d.png)
