### ISSUE TITLE
顶栏偶尔卡死

### ISSUE THREAD

**Issue by EchoGroot** [SeptemberHX/dde-top-panel#43]
一周会遇见几次，顶栏上的时间不再变化，对顶栏任何点击都没有响应。这时在启动器里启动顶栏，顶栏就会重启，回归正常。
请问这个有日志吗？看看能否找到原因

**Comment by SeptemberHX** [comment]
没有埋过日志点。建议先删掉顶栏上所有的插件，看看是不是插件导致的。

**Comment by peigen** [comment]
> 没有埋过日志点。建议先删掉顶栏上所有的插件，看看是不是插件导致的。

我自己测试，大概是libtray.so插件导致的，cpu占用率6%左右，但是会卡住整个界面。
大概是有死循环什么的吧。但是这个插件非常之重要。

**Comment by SeptemberHX** [comment]
> > 没有埋过日志点。建议先删掉顶栏上所有的插件，看看是不是插件导致的。
> 
> 我自己测试，大概是libtray.so插件导致的，cpu占用率6%左右，但是会卡住整个界面。 大概是有死循环什么的吧。但是这个插件非常之重要。

1. panel 插件里的 libtray.so 是和系统版本一致的吗？每次系统更新是不会自动复制过去的
2. 是否使用了系统的 libdatetime.so 插件？目前观测到该插件会导致 panel 不定时重复卡死，出现 panel 上的时间相较于系统时间的差距越来越大
3. libtray.so 里有哪些具体的应用？

**Comment by peigen** [comment]
> > > 没有埋过日志点。建议先删掉顶栏上所有的插件，看看是不是插件导致的。
> > 
> > 
> > 我自己测试，大概是libtray.so插件导致的，cpu占用率6%左右，但是会卡住整个界面。 大概是有死循环什么的吧。但是这个插件非常之重要。
> 
> 1. panel 插件里的 libtray.so 是和系统版本一致的吗？每次系统更新是不会自动复制过去的
> 2. 是否使用了系统的 libdatetime.so 插件？目前观测到该插件会导致 panel 不定时重复卡死，出现 panel 上的时间相较于系统时间的差距越来越大
> 3. libtray.so 里有哪些具体的应用？

用系统版本问题完美解决

**Comment by EchoGroot** [comment]
嗦嘎
