### ISSUE TITLE
新特性请求

### ISSUE THREAD

**Issue by danny2jenny** [SeptemberHX/dde-top-panel#44]
大侠，全局菜单菜单背景，菜单背景，不是panel背景，是否可以增加一个背景颜色设置。因为有些菜单项目图标和背景冲突，看不出来了。例如 jetbrains 的全家桶的菜单上面的图标和菜单背景是一样的颜色，看不出来。

谢谢。

**Comment by SeptemberHX** [comment]
菜单的背景色是跟随系统的，深色-浅色，不是 dde-top-panel 控制的

建议 jetbrains 插件中心装插件：material icons，装上后菜单的图标就不是灰色调了，看的还是蛮清楚的

**Comment by danny2jenny** [comment]
谢谢
