### ISSUE TITLE
多屏下的显示问题

### ISSUE THREAD

**Issue by wtf4007** [SeptemberHX/dde-top-panel#46]
多屏，非相同分辨率，使用屏幕缩放，顶栏显示不正确

**Comment by SeptemberHX** [comment]
具体的显示效果是什么样的呢？一个屏幕正常，一个屏幕不正常，还是都不正常？不正常的话，是显示的长度太长导致溢出屏幕显示范围，还是太短呢？

**Comment by wtf4007** [comment]
> 正常

两个屏幕都不正常。主屏显示的长度太短，副屏太常

**Comment by SeptemberHX** [comment]
能够截个图？我想看看屏幕宽多少像素以及panel宽多少像素，可能是缩放计算错了

**Comment by wtf4007** [comment]
主屏 1920×1080
副屏 1680×1050


主屏上应该是被副屏的 panel给 遮住了，也许不是长度问题，而是位置问题







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SeptemberHX/dde-top-panel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月12日(星期三) 上午10:54
***@***.***&gt;;
抄送:&nbsp;"Leon ***@***.******@***.***&gt;;
主题:&nbsp;Re: [SeptemberHX/dde-top-panel] 多屏下的显示问题 (Issue #46)





 
能够截个图？我想看看屏幕宽多少像素以及panel宽多少像素，可能是缩放计算错了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SeptemberHX** [comment]
那可能是副屏位置计算错了，缩放情况呢，是否设置了缩放比？

**Comment by IT-Tagore** [comment]
你好开发者，我的主屏分辨率是2560x1440,副屏是1920x1080,目前主屏显示正常的，副屏的panel左边在主屏panel的上面，叠在主屏panel的上面了，然后副屏panel剩余的一半显示不全，只有副屏顶部宽度的60%左右。

**Comment by SeptemberHX** [comment]
> 

有没有设置屏幕缩放？找个截图工具，看一看副屏幕空出来的宽度具体是多少像素。

**Comment by SeptemberHX** [comment]
> 你好开发者，我的主屏分辨率是2560x1440,副屏是1920x1080,目前主屏显示正常的，副屏的panel左边在主屏panel的上面，叠在主屏panel的上面了，然后副屏panel剩余的一半显示不全，只有副屏顶部宽度的60%左右。

有没有设置屏幕缩放？找个截图工具，看一看副屏幕空出来的宽度具体是多少像素。

**Comment by IT-Tagore** [comment]
抱歉我的副屏在公司，我现在已经在家里了，等我下周一去公司给你反馈，目前我的主屏缩放是1.25,副屏默认缩放，

**Comment by wtf4007** [comment]
之前我给你回复的邮件里是有截图的。邮件时间 2022年1月12日（星期三）上午10 : 59

**Comment by IT-Tagore** [comment]
![截图_选择区域_20220117094925](https://user-images.githubusercontent.com/60809013/149688761-68bb9ec7-8993-4a5a-a035-4132094cbabd.jpg)
![截图_dde-top-panel_20220117094938](https://user-images.githubusercontent.com/60809013/149688770-30f98055-04a5-4479-8be7-d6b88ad134fb.jpg)

**Comment by IT-Tagore** [comment]
已反馈

**Comment by IT-Tagore** [comment]
1：在反馈一个问题，双击top-panel用户响应层会卡死，一些已经执行的操作仍会执行，用户无法操作界面，按下回车键即可恢复正常，
2：锁屏或静止一段时间top-panel会消失，需要重新手动运行。

**Comment by SeptemberHX** [comment]
你们的系统版本是多少啊，我最新版在两个 4k 屏幕上，两个屏幕平行布局，缩放分别设置成 x1, x1.5, x1.75, x2 都没有出现错位的情况。

但我大致明白是什么导致的，移动的时候如果没有把缩放比例计算进去就会出现错位情况：(2560 - 2560 / 1.25) / (1920 / 1.25) = 1 - 0.666  大致就是 1920 屏幕panel宽度是 66%

**Comment by wtf4007** [comment]
20.3




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SeptemberHX/dde-top-panel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月17日(星期一) 中午11:43
***@***.***&gt;;
抄送:&nbsp;"Leon ***@***.******@***.***&gt;;
主题:&nbsp;Re: [SeptemberHX/dde-top-panel] 多屏下的显示问题 (Issue #46)





 
你们的系统版本是多少啊，我最新版在两个 4k 屏幕上，两个屏幕平行布局，缩放分别设置成 x1, x1.5, x1.75, x2 都没有出现错位的情况。
 
但我大致明白是什么导致的，移动的时候如果没有把缩放比例计算进去就会出现错位情况：(2560 - 2560 / 1.25) / (1920 / 1.25) = 1 - 0.666  大致就是 1920 屏幕panel宽度是 66%
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SeptemberHX** [comment]
麻烦再贴一下 qtbase5-dev 的版本号。

`apt info qtbase5-dev` 查看

**Comment by wtf4007** [comment]
Package: qtbase5-dev
Version: 5.15.1.8-1+dde
Priority: optional
Section: libdevel
Source: qtbase-opensource-src





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SeptemberHX/dde-top-panel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月17日(星期一) 中午11:47
***@***.***&gt;;
抄送:&nbsp;"Leon ***@***.******@***.***&gt;;
主题:&nbsp;Re: [SeptemberHX/dde-top-panel] 多屏下的显示问题 (Issue #46)





 
麻烦再贴一下 qtbase5-dev 的版本号。
 
apt info qtbase5-dev 查看
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SeptemberHX** [comment]
> 1：在反馈一个问题，双击top-panel用户响应层会卡死，一些已经执行的操作仍会执行，用户无法操作界面，按下回车键即可恢复正常， 2：锁屏或静止一段时间top-panel会消失，需要重新手动运行。

第1个问题应该是有双击顶栏后拖拽的操作吧，这个目前没找大卡死的原因，拖拽的代码是直接调用的接口，在KDE等其他桌面上都可以，之前的一些版本也可以，但现在不知道为啥不好使了，可以在 panel 设置中取消勾选 ”拖拽空白区域移动最大化窗口“ 选项防止误触发；

第2个问题需要我后续调查一下，暂时原因不明

**Comment by SeptemberHX** [comment]
和我的版本号也一致。。那还有一种可能，是 panel 开机自启的时候，屏幕信息还没有初始化完成，或者之后的屏幕信息发生了变化（目前 panel 没有监控屏幕分辨率、布局之类的做自适应）。

桌面启动后，右键 panel，然后重启 panel，看看是否依然错位？

**Comment by wtf4007** [comment]
依然错位




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月17日(星期一) 中午11:56
收件人: ***@***.***&gt;; 
抄送: "Leon ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SeptemberHX/dde-top-panel] 多屏下的显示问题 (Issue #46)





 
和我的版本号也一致。。那还有一种可能，是 panel 开机自启的时候，屏幕信息还没有初始化完成，或者之后的屏幕信息发生了变化（目前 panel 没有监控屏幕分辨率、布局之类的做自适应）。
 
桌面启动后，右键 panel，然后重启 panel，看看是否依然错位？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by IT-Tagore** [comment]
刚我把主屏的缩放从1.25调到了1,正常了

**Comment by wtf4007** [comment]
遗憾了。按描述的步骤操作了一遍，问题依旧```。
我是这么操作的。移除副屏，将缩放调回1,注销，重进，将缩放调为1.25,启动panel，接入副屏。

**Comment by 0RAJA** [comment]
感谢！完美解决！

> 遗憾了。按描述的步骤操作了一遍，问题依旧```。 我是这么操作的。移除副屏，将缩放调回1,注销，重进，将缩放调为1.25,启动panel，接入副屏。

**Comment by 0RAJA** [comment]
> Reference in new is

感谢！完美解决~

**Comment by IrisYagami** [comment]
多屏显示中竖屏的情况会出现类似的展示问题，竖屏最高点高于横向屏时只有竖屏能显示一部分的bar

**Comment by SeptemberHX** [comment]
> 多屏显示中竖屏的情况会出现类似的展示问题，竖屏最高点高于横向屏时只有竖屏能显示一部分的bar

两个屏幕的分辨率一样么

**Comment by wtf4007** [comment]
> > 多屏显示中竖屏的情况会出现类似的展示问题，竖屏最高点高于横向屏时只有竖屏能显示一部分的bar
> 
> 两个屏幕的分辨率一样么

我之前反馈的不行，也是因为两个屏幕分辨率不一样。但并非竖屏，两个屏都是横屏。

所以就是当两个显示器都是横屏，且有对屏幕进行缩放，会导致pannel定位错误。

**Comment by SeptemberHX** [comment]
好的，这两天我找两个屏幕试一试

**Comment by SeptemberHX** [comment]
[dde-top-panel-0.6.7-Linux.deb.zip](https://github.com/SeptemberHX/dde-top-panel/files/9432608/dde-top-panel-0.6.7-Linux.deb.zip)

试试看有没有修好。我在 4k + 1080p 双屏 1.25 倍缩放下测试是正常的了

**Comment by wtf4007** [comment]
> 

完美解决。栓Q！
