### ISSUE TITLE
新创建的工作区不会自动启动panel

### ISSUE THREAD

**Issue by flywish** [SeptemberHX/dde-top-panel#47]
使用多任务视图，新建工作区，新的工作区是否也能自动使用panel，还需要手动在该工作区启动panel。是否可以添加相关设置？

**Comment by SeptemberHX** [comment]
需要手动安装 systemsettings (kde 的系统设置)，然后创建新的窗口规则，窗口选择 panel，然后设置成在每个工作区都显示即可。
