### ISSUE TITLE
Visualization errors and computer freezing after last Deepin OS update

### ISSUE THREAD

**Issue by ibraGut** [SeptemberHX/dde-top-panel#48]
The date and time appears too big and the "global menu" does not appears instantly. When closing the respective program, the global menu remains a few seconds and then go. When right click on the panel, nothing comes up but just an empty square, then the computer does not respond for several minutes. After killing the panel, everything is correct with the system. Close/maximize/minimize buttons do not appear either.

**Comment by SeptemberHX** [comment]
`dde-top-panel` is not compatible with `libdatetime.so`. It should work again after removing `libdatetime.so` in the plugins dir of `dde-top-panel`.

**Comment by ibraGut** [comment]
It worked! So I'll keep the date and time at the dock. Thanks!
