### ISSUE TITLE
时间显示问题

### ISSUE THREAD

**Issue by smallodd** [SeptemberHX/dde-top-panel#51]
![image](https://user-images.githubusercontent.com/13759794/157781809-c8393af0-647b-4db0-9763-5dd0d4d11de7.png)
![image](https://user-images.githubusercontent.com/13759794/157781847-854f2b84-d694-4034-b138-18b55589aa5d.png)
如图 任务栏显示的时间和dde-top-panel显示的时间不一致 。
系统版本
![image](https://user-images.githubusercontent.com/13759794/157782004-71071149-699d-4614-b37e-d5bed245e430.png)

**Comment by SeptemberHX** [comment]
插件 dde-top-panel 没法控制的，显示内容更新都是插件自己完成的，所以如果只是单纯的时间错误那问题不在 panel。

1. 先检查一下 panel 插件目录下的时间插件是不是和系统中的一致
2. 这个问题是 panel 启动时就会出现吗？还是说一开始是准确的，一段时间后就不准确，且差异会随着运行时间增加而增大？

**Comment by smallodd** [comment]
一开始是准确的，一段时间后是不准确的，目测差异会随着运行时间增加而增大，例如现在时间为
![image](https://user-images.githubusercontent.com/13759794/157810980-9452916f-19c8-43f7-8bbf-a27be352dd83.png)
但是插件时间为
![image](https://user-images.githubusercontent.com/13759794/157811016-750238f7-8c55-4065-9ff3-0daa322fc8fc.png)

panel插件所在目录为
![image](https://user-images.githubusercontent.com/13759794/157811713-d78d316a-e9c4-4f2f-bd2c-bb63ec006f34.png)


系统时间插件所在目录为
![image](https://user-images.githubusercontent.com/13759794/157811761-1d00c9c4-6934-49f8-81b3-19dea21c465e.png)

**Comment by SeptemberHX** [comment]
试了一下，不知道我们的问题一不一样。我这边确实出现了更新问题，而且伴随着 panel 被卡死或者响应很慢的情况。从源码上看，主要原因是 libdatetime.so 在不断调整它的高度。在 dock 上因为高度足够，所以不会出问题，但是在 panel 上由于高度不足，导致它不断重复更改自己的字号刷新，进而阻塞或减缓了 panel 的正常工作，包括它自己的更新。

建议不使用官方的时间插件，因为 panel 高度不满足 libdatetime.so 的最低高度要求。可以换一下其他人的插件：https://bbs.deepin.org/post/198163

**Comment by smallodd** [comment]
我试试 ，多谢大佬
