### ISSUE TITLE
0.6.6版本默认显示图标无法更改成功

### ISSUE THREAD

**Issue by qingee** [SeptemberHX/dde-top-panel#52]
0.6.6版本默认显示图标无法更改成功，重启Panel后就恢复到深度的图标了

**Comment by SeptemberHX** [comment]
贴一下配置文件的内容：`~/.config/dde-top-panel/` 里应该有个 *.ini 文件

**Comment by qingee** [comment]
![image](https://user-images.githubusercontent.com/36303077/165092983-bd1a746f-427e-444d-98f9-71bdd68cc87d.png)
![image](https://user-images.githubusercontent.com/36303077/165093081-62b030ce-3dac-4168-bb5b-389e8dbf364c.png)
没有你说的这个文件，只有这个文件及内容

**Comment by qingee** [comment]
试了一下改里面的图标内容,重启后又被自动覆写文件了

**Comment by qingee** [comment]
把跟随系统主题的选项关闭就好啦，更改为SVG图标后显示打太小了，怎么更改图标的大小啊？

**Comment by SeptemberHX** [comment]
大概能想到问题在哪了，你的屏幕缩放是都少？可能是我没对这三个图标做高分屏处理

**Comment by qingee** [comment]
1366x768,是这四个图标都很小,只能用图片才不会小，用svg就很小
