### ISSUE TITLE
全局菜单与dde新桌面互斥

### ISSUE THREAD

**Issue by 878547387** [SeptemberHX/dde-top-panel#58]
全局菜单依赖的QT4组件与最新dde桌面排斥了，作者看看能不能适配一下新组件

**Comment by SeptemberHX** [comment]
没听明白哦，能否配上个截图或者动图之类的？

**Comment by 878547387** [comment]
![](https://oss.zhangshunkang.cn/img/微信图片_20221109154604.jpg)
![](https://oss.zhangshunkang.cn/img/微信图片_20221109154555.jpg)
最新内测的桌面升级了很多Qt5的模块，然后与libqtcore4排斥，存在这个的话升级就会出现问题。然后我看dde-golbalmenu-service依赖这些组件，更新好系统后，sudo apt autoremove就会自动把globalmenu删除。

**Comment by 878547387** [comment]
就是这个插件依赖的那些东西，在最新的桌面环境中，已经不能使用了，否则就会出现问题。我看有的人就因为这些依赖问题升级崩了。

**Comment by SeptemberHX** [comment]
那可能得更新一下依赖信息，然后重新编译个安装包了，是 v20 的内测版本对吧？

**Comment by 878547387** [comment]
> 那可能得更新一下依赖信息，然后重新编译个安装包了，是 v20 的内测版本对吧？
对的，最新内测版。

**Comment by SeptemberHX** [comment]
[dde-globalmenu-service-1.0.0-Linux.deb.zip](https://github.com/SeptemberHX/dde-top-panel/files/9969350/dde-globalmenu-service-1.0.0-Linux.deb.zip)

试试看，应该是 appmenu-qt 依赖导致的，不装它好像对全局菜单也没什么影响。

**Comment by 878547387** [comment]
cool,使用正常，没有出现依赖问题。谢谢您

**Comment by SeptemberHX** [comment]
https://github.com/SeptemberHX/dde-globalmenu-service/releases 发布了新版本，和上面那个一样，只不过版本号改成了 v1.0.1
