### ISSUE TITLE
panel工作区切换问题

### ISSUE THREAD

**Issue by JiakaiYang** [SeptemberHX/dde-top-panel#59]
deepin v20.8
panel v0.6.8
在切换工作区的过程中，发现只能在一个工作区里使用panel。其他工作区panel不可用，但是可以在每个工作区打开一个panel，但是当删除工作区的时候，panel会卡死，  dde的窗口特效会奔溃而关闭。而且 打开多个panel时，不同工作区的程序无法通过panel菜单栏操作，否则会卡死

**Comment by SeptemberHX** [comment]
需要手动安装 systemsettings (kde 的系统设置)，然后创建新的窗口规则，窗口选择 panel，然后设置成在每个工作区都显示即可。

**Comment by JiakaiYang** [comment]
![image](https://user-images.githubusercontent.com/79317176/208113912-28c64423-df3e-4cb8-b95e-fb5683253f8c.png)
![image](https://user-images.githubusercontent.com/79317176/208114042-ee6e9cac-b230-4373-a6d1-ded6873fe2e9.png)
![image](https://user-images.githubusercontent.com/79317176/208114118-36abcd3c-2e36-4cb0-84c5-ace6e33627ab.png)
