### ISSUE TITLE
After v 0.6.7 bar does not behave correctly when dock is placed on left

### ISSUE THREAD

**Issue by ibraGut** [SeptemberHX/dde-top-panel#62]
In Deepin 20.8, when using the left placed dde-dock (either fashion or efficient mode), the bar does not change the empty space to the left. I replicated the problem in two PCs with different screen size (1366x768 and 2560x1600) with the same result. After a fresh install the problem remains. It happens in versions 0.6.7 and 0.6.8. I did not check this in other deepin versions, only 20.8. Please check the screenshot. 

![Screenshot_20230313130241](https://user-images.githubusercontent.com/73623191/224806879-f262cdd3-3c1e-4e22-99b2-24661c4cebcf.png)

**Comment by SeptemberHX** [comment]
It should be fixed now. You can test it with the attached package: [dde-top-panel-0.6.8-Linux.deb.zip](https://github.com/SeptemberHX/dde-top-panel/files/11301434/dde-top-panel-0.6.8-Linux.deb.zip)

<img width="1916" alt="image" src="https://user-images.githubusercontent.com/18042424/233787595-03e226a9-43cc-41be-8a4a-b7f86354217a.png">

**Comment by ibraGut** [comment]
Fixed! thanks!
