### ISSUE TITLE
当任务栏在左侧时dde-top-panel左右没有铺满窗口

### ISSUE THREAD

**Issue by zhanfei945** [SeptemberHX/dde-top-panel#64]
问题反馈两个
当任务栏在左侧时dde-top-panel左右没有铺满窗口
![图片](https://user-images.githubusercontent.com/64345449/232802742-ada2bb2d-f7f6-4428-b722-b7e7bddd6c58.png)
还有一个问题就是取消选择“仅在窗口全屏时显示”，顶栏就没有三大按钮了
![图片](https://user-images.githubusercontent.com/64345449/232805029-f50ffe53-f1e6-4082-8fd2-f11711b25857.png)
![图片](https://user-images.githubusercontent.com/64345449/232802975-cf227705-8ca3-478b-9b63-0d9a88a903a3.png)

**Comment by SeptemberHX** [comment]
现在 panel 没有铺满的问题应该修复了。另外一个应该是翻译问题，本意上是显示/不显示控制按钮，也一并改过来了：[dde-top-panel-0.6.8-Linux.zip](https://github.com/SeptemberHX/dde-top-panel/files/11301457/dde-top-panel-0.6.8-Linux.zip)


<img width="1919" alt="image" src="https://user-images.githubusercontent.com/18042424/233788123-30eab3e5-e7c0-4232-8786-120a223d1e83.png">
