### ISSUE TITLE
Global menu suggestion - Only show menu when mouse hovers

### ISSUE THREAD

**Issue by simnandez** [SeptemberHX/dde-top-panel#7]
It could be a good functionality, show the global menu in the top panel mouse over, otherwise show the window title.

**Comment by SeptemberHX** [comment]
I have considered this. However, in my daily usage, I found some facts:

1. When current window is not maximized, the window has title bar, which means it is necessary to show the title bar on the panel
2. When current window is maximized, which means I am focuing on current application, the window title cannot provide useful information. And the menu is triggered frequently.

Thus, I prefer to always show the global menu when the application has global menu.

However, I will leave this issue open to check whether there are more people need this.

**Comment by simnandez** [comment]
@SeptemberHX  An example: If we have 3 or more not maximized windows, we may not know which is the one with the focus, so we do not know which top panel menu of the 3 is showing. If it showed the window title, we would know what it is. I think it is a good case where the hover menu is useful.

It is common to have several opened windows, even on different monitors, and that, for example, if you receive a phone call at the end of it, you do not know where the focus was...

**Comment by SeptemberHX** [comment]
@simnandez Last few days I faced the situation with multi maximized window, and I was confused with each other soon. This made me reconsider your suggestion.

Now I have added an optional preference for "Show menu for maximized window when mouse hovers" in the latest release. 

However, for other windows that are not maximized the menu is always shown.
